---
inputs:
  - type: git
    service: ${PIPELINE_REPO}
    branch: ${PIPELINE_REPO_BRANCH}
    path: .pipeline
  - type: git
    service: ${TEKTON_CATALOG_REPO}
    branch: ${DEFINITIONS_BRANCH}
    path: git
  - type: git
    service: ${TEKTON_CATALOG_REPO}
    branch: ${DEFINITIONS_BRANCH}
    path: cloudfoundry
  - type: git
    service: ${TEKTON_CATALOG_REPO}
    branch: ${DEFINITIONS_BRANCH}
    path: toolchain
triggers:
  - type: git
    name: commit-push
    eventListener: ${GIT_COMMIT_EVENT_LISTENER_NAME}
    service: ${SAMPLE_REPO}
    branch: ${APP_REPO_BRANCH}
    events: { "push": true }
  - type: manual
    name: manual-run
    eventListener: manual-run
    properties:
      - name: branch
        type: text
        value: ${APP_REPO_BRANCH}
properties:
  - type: text
    name: ibmcloud-api
    value: ${IBMCLOUD_API}
  - type: text
    name: cf-app
    value: ${CF_APP_NAME}
  - type: text
    name: cf-org
    value: ${PROD_ORG_NAME}
  - type: text
    name: cf-space
    value: ${PROD_SPACE_NAME}
  - type: text
    name: region
    value: ${PROD_REGION_ID}
  - type: secure
    name: toolchain-apikey
    value: ${API_KEY}
  - type: secure
    name: apikey
    value: ${API_KEY}
